inherit_from: .rubocop_todo.yml

plugins: rubocop-rails

Metrics/ClassLength:
  Exclude:
    - app/commands/**

Rails:
  Enabled: true
AllCops:
  NewCops: enable
  Exclude:
    - db/*schema.rb
    - db/migrate/*
    - bin/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/MethodLength:
  Enabled: false
Layout/LineLength:
  Max: 140
Metrics/AbcSize:
  Enabled: false

Layout/ConditionPosition:
  Enabled: true
Lint/AssignmentInCondition:
  Enabled: true

Documentation:
  Enabled: false
