inherit_from: .rubocop_todo.yml

plugins: rubocop-rails

Rails:
  Enabled: true
  Exclude:
    - db/schema.rb
    - db/migrate/*

Metrics/MethodLength:
  Enabled: false
Layout/LineLength:
  Max: 140
Metrics/AbcSize:
  Enabled: false

Layout/ConditionPosition:
  Enabled: true
Lint/AssignmentInCondition:
  Enabled: true

Documentation:
  Enabled: false
