language: ruby
env:
 - DB=postgresql
rvm:
  - 2.1.1
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database masha_test' -U postgres

script:
  - bundle exec rubocop app/
