language: ruby
addons:
  postgresql: "10"
cache: bundler
env:
 - DB=postgresql
services:
- postgresql
before_install:
  - gem update --system
  - gem install bundler
  - bundle config git.allow_insecure true
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database masha_test' -U postgres
  - bundle exec rake db:schema:load
  - yarn install

script:
  - bundle exec rake
  # - RAILS_ENV=production bundle exec rake assets:clean assets:precompile
  # - bundle exec rubocop app/
