site :opscode

cookbook 'build-essential'
cookbook 'nginx'
cookbook 'runit'
cookbook 'unicorn'
cookbook 'git'
cookbook 'postgresql'
cookbook 'application_ruby'
cookbook 'imagemagick'
cookbook 'ubuntu'
cookbook 'users'
cookbook 'ruby_build'
cookbook 'rbenv' #, git: 'git://github.com/zozi/chef-rbenv.git'
cookbook 'ssh_known_hosts'
