services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    environment:
      DATABASE_URL: postgres:5443/masha_development
      MASHA_REDIS_CACHE_STORE_URL: redis://redis:6379

  redis:
    image: redis

