development:
  secret_key_base: "a_long_random_hexadecimal_string_for_development"

test:
  secret_key_base: "another_random_hexadecimal_string_for_testing"

production:
  # In a production environment, it's best to use an environment variable
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
