defaults: &defaults
  github_repo: https://github.com/brandymint/masha
  title: MASHA
  asset_host: http://masha.brandymint.ru/

  sidekiq_redis:
    url: <%= "redis://#{ENV['REDIS_HOST'] || '127.0.0.1'}:6379/3" %>

  default_url_options: &default_url_options
    host: masha.brandymint.ru
    port: 80

  mail_from: masha@brandymint.ru

development:
  <<: *defaults
  default_url_options: &default_url_options
    host: <%= ENV['APP_HOST'] || 'localhost' %>
    port: 80

test:
  <<: *defaults
  capybara:
    port: 57500

production:
  <<: *defaults

staging:
  <<: *defaults
