name: Build And Push Image
on:
  # Вызвал пользователь
  workflow_dispatch:
    inputs:
      tag:
        type: string

  # Вызвали из другого пайплайна
  workflow_call:
    inputs:
      tag:
        type: string

env:
  INFRA_REPO: git@github.com:brandymint/infra.git
  WORKFLOW: deploy-app.yml
  STAGE: default

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v5
      - run: |
          gh --repo ${{ env.INFRA_REPO }} workflow run ${{ env.WORKFLOW }} -F tag=${{ needs.build.outputs.version }} -F app=${{ github.event.repository.name }} -F stage=${{ env.STAGE }}
          runId=$(gh --repo ${{ env.INFRA_REPO }} run list --workflow=${{ env.WORKFLOW }} --limit 1 --json databaseId -q '.[].databaseId')
          gh --repo ${{ env.INFRA_REPO }} run watch --exit-status ${runId}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
